Feature/delete error messages
flowlink/quiet_logistics_integration pull request #32
Opened 2019-09-09 19:41 UTC by msalo3

Adds deleting error messages by using a subsequent request to FlowLink. This allows us to ensure FlowLink has the error message before deletion.
Uses JSON in case there are some strange characters. 

Adds extra logging on all calls that include the business unit name to help narrow down what company may be having issues

2019-09-09 19:43 UTC, gorandev requested changes
Do we need all the "puts" on a working version? At least make it write to logger, maybe upon checking some ENV var...

2019-09-09 20:11 UTC, gorandev approved these changes

2019-09-09 20:53 UTC, raysapida commented
With this implementation, does that mean each workflow will either delete error messages or receive new ones?

2019-09-10 16:49 UTC, raysapida approved these changes

2019-09-10 16:50 UTC, merged